import { InternalRole } from '../generated/prisma/enums.js';

export interface CommandDefinition {
  command: string;
  description: string;
  role: InternalRole;
  category: 'Mitglieder' | 'Moderatoren' | 'Administratoren' | 'Eigentümer';
}

export const commandRegistry: readonly CommandDefinition[] = [
  {
    command: 'help',
    description: 'Verfügbare Befehle',
    role: InternalRole.MEMBER,
    category: 'Mitglieder',
  },
  {
    command: 'rules',
    description: 'Gruppenregeln anzeigen',
    role: InternalRole.MEMBER,
    category: 'Mitglieder',
  },
  {
    command: 'ki',
    description: 'Der KI eine Frage stellen',
    role: InternalRole.MEMBER,
    category: 'Mitglieder',
  },
  {
    command: 'regeln',
    description: 'Gruppenregeln anzeigen',
    role: InternalRole.MEMBER,
    category: 'Mitglieder',
  },
  {
    command: 'userinfo',
    description: 'Eigene Benutzerinformationen',
    role: InternalRole.MEMBER,
    category: 'Mitglieder',
  },
  {
    command: 'warnings',
    description: 'Eigene Verwarnungen anzeigen',
    role: InternalRole.MEMBER,
    category: 'Mitglieder',
  },
  {
    command: 'nightstatus',
    description: 'Nachtmodus anzeigen',
    role: InternalRole.MEMBER,
    category: 'Mitglieder',
  },
  {
    command: 'commands',
    description: 'Eigene Gruppenbefehle anzeigen',
    role: InternalRole.MEMBER,
    category: 'Mitglieder',
  },
  {
    command: 'mydata',
    description: 'Gespeicherte eigene Daten',
    role: InternalRole.MEMBER,
    category: 'Mitglieder',
  },
  {
    command: 'deletemydata',
    description: 'Entfernbare Daten löschen',
    role: InternalRole.MEMBER,
    category: 'Mitglieder',
  },
  {
    command: 'warn',
    description: 'Nutzer verwarnen',
    role: InternalRole.MODERATOR,
    category: 'Moderatoren',
  },
  {
    command: 'unwarn',
    description: 'Letzte Warnung entfernen',
    role: InternalRole.MODERATOR,
    category: 'Moderatoren',
  },
  {
    command: 'mute',
    description: 'Nutzer stummschalten',
    role: InternalRole.MODERATOR,
    category: 'Moderatoren',
  },
  {
    command: 'tmute',
    description: 'Zeitlich stummschalten',
    role: InternalRole.MODERATOR,
    category: 'Moderatoren',
  },
  {
    command: 'unmute',
    description: 'Stummschaltung aufheben',
    role: InternalRole.MODERATOR,
    category: 'Moderatoren',
  },
  {
    command: 'ban',
    description: 'Nutzer sperren',
    role: InternalRole.MODERATOR,
    category: 'Moderatoren',
  },
  {
    command: 'tban',
    description: 'Zeitlich sperren',
    role: InternalRole.MODERATOR,
    category: 'Moderatoren',
  },
  {
    command: 'unban',
    description: 'Sperre aufheben',
    role: InternalRole.MODERATOR,
    category: 'Moderatoren',
  },
  {
    command: 'kick',
    description: 'Nutzer entfernen',
    role: InternalRole.MODERATOR,
    category: 'Moderatoren',
  },
  {
    command: 'setrules',
    description: 'Regeln festlegen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'inaktiv',
    description: 'Inaktive Mitglieder verwalten',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'setupgroup',
    description: 'Regeln und Schutz einrichten',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'nameguard',
    description: 'Namensschutz ein- oder ausschalten',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'addforbiddenname',
    description: 'Verbotenen Namen hinzufügen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'removeforbiddenname',
    description: 'Verbotenen Namen entfernen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'forbiddennames',
    description: 'Verbotene Namen anzeigen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'welcome',
    description: 'Begrüßung ein- oder ausschalten',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'antilink',
    description: 'Linkschutz konfigurieren',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'allowdomain',
    description: 'Domain erlauben',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'removedomain',
    description: 'Erlaubte Domain entfernen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'allowuser',
    description: 'Nutzer vom Schutz ausnehmen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'removealloweduser',
    description: 'Nutzerausnahme entfernen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'nightmode',
    description: 'Nachtmodus konfigurieren',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'setclosetime',
    description: 'Schließzeit festlegen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'setopentime',
    description: 'Öffnungszeit festlegen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'setlogchannel',
    description: 'Admin-Log-Kanal festlegen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'addfilter',
    description: 'Wortfilter erstellen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'presetfilters',
    description: 'Standard-Wortfilter schalten',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'removefilter',
    description: 'Wortfilter entfernen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'filters',
    description: 'Wortfilter anzeigen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'promotemod',
    description: 'Moderator ernennen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'trust',
    description: 'Nutzer vertrauen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'untrust',
    description: 'Vertrauen entfernen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'clearwarnings',
    description: 'Alle Warnungen löschen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'schedulemessage',
    description: 'Automatische Nachricht planen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'scheduledmessages',
    description: 'Geplante Nachrichten anzeigen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'deletescheduledmessage',
    description: 'Geplante Nachricht löschen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'addcommand',
    description: 'Eigenen Befehl anlegen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'removecommand',
    description: 'Eigenen Befehl entfernen',
    role: InternalRole.ADMIN,
    category: 'Administratoren',
  },
  {
    command: 'demotemod',
    description: 'Moderator zurückstufen',
    role: InternalRole.OWNER,
    category: 'Eigentümer',
  },
] as const;
