import type { Database } from '../../database/client.js';
import type { RedisClient } from '../../services/redis.js';
import { normalizeName } from '../../services/name-guard.js';

export const POLITICAL_DISPLAY_NAME_PRESETS = [
  'afd',
  'cdu',
  'csu',
  'spd',
  'fdp',
  'bsw',
  'bündnis 90',
  'die grünen',
  'die linke',
  'akp',
  'ak parti',
  'chp',
  'mhp',
  'iyi parti',
  'dem parti',
  'hdp',
  'saadet partisi',
  'yeniden refah',
  'zafer partisi',
  'hüda par',
  'huda par',
  'pkk',
  'ypg',
  'graue wölfe',
  'bozkurt',
  'maga',
  'nazi',
  'neonazi',
  'heil hitler',
  'biji serok apo',
  'reis erdoğan',
  'reis erdogan',
  'free palestine',
  'from the river to the sea',
] as const;

export const INSULTING_DISPLAY_NAME_PRESETS = [
  'arschloch',
  'hurensohn',
  'wichser',
  'wixxer',
  'fotze',
  'missgeburt',
  'drecksau',
  'schlampe',
  'bastard',
  'nutte',
  'hure',
  'hurentochter',
  'arschficker',
  'dreckschwein',
  'wichskopf',
  'vollidiot',
  'idiot',
  'schwanzlutscher',
  'nuttenkind',
  'orospu',
  'oruspu',
  'pezevenk',
  'şerefsiz',
  'serefsiz',
  'piç',
  'puşt',
  'kahpe',
  'yavşak',
  'sikik',
  'siktir',
  'amk',
  'götveren',
  'götlek',
  'yarak',
  'yarrak',
  'ibne',
  'gavat',
  'kaltak',
  'kaşar',
  'namussuz',
  'gerizekalı',
  'salak',
  'ahmak',
  'aptal',
  'orospu çocuğu',
  'qehpe',
  'qehpê',
  'kurê qehpê',
  'bêşeref',
  'beseref',
  'haramzade',
  'ehmeq',
  'bêaqil',
  'qehbik',
  'tu kûçik',
  'scheiß islam',
  'scheiss islam',
  'allahını sikeyim',
  'allahini sikeyim',
] as const;

export const DISPLAY_NAME_PRESETS = [
  ...POLITICAL_DISPLAY_NAME_PRESETS,
  ...INSULTING_DISPLAY_NAME_PRESETS,
] as const;

export async function setDisplayNamePresets(
  database: Database,
  redis: RedisClient,
  groupId: string,
  actorTelegramId: bigint,
): Promise<void> {
  await database.$transaction(
    DISPLAY_NAME_PRESETS.map((pattern) => {
      const normalized = normalizeName(pattern);
      return database.forbiddenName.upsert({
        where: {
          groupId_normalizedPattern: { groupId, normalizedPattern: normalized.normalized },
        },
        create: {
          groupId,
          pattern,
          normalizedPattern: normalized.normalized,
          compactPattern: normalized.compact,
          createdByTelegramId: actorTelegramId,
        },
        update: {
          pattern,
          compactPattern: normalized.compact,
          enabled: true,
          deletedAt: null,
        },
      });
    }),
  );
  await redis.del(`forbidden-names:${groupId}`);
}
